<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProduitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('produits')->insert([
            [
                "nom"=>"Ballon World Cup",
                "categorie"=>"Ballons",
                "couleur"=>"Blanc",
                "image"=>"produit1",
                "prix"=>50,
                "promo"=> null,
                "stock"=>12,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Maillot Real Madrid",
                "categorie"=>"Maillots",
                "couleur"=>"Violet",
                "image"=>"produit2",
                "prix"=>120,
                "promo"=> null,
                "stock"=>7,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Gants gardien",
                "categorie"=>"Accessoires",
                "couleur"=>"Jaune",
                "image"=>"produit3",
                "prix"=>35,
                "promo"=> null,
                "stock"=>7,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Protèges tibia",
                "categorie"=>"Accessoires",
                "couleur"=>"Jaune",
                "image"=>"produit4",
                "prix"=>40,
                "promo"=> 20,
                "stock"=>12,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Maillot Real Madrid",
                "categorie"=>"Maillots",
                "couleur"=>"Blanc",
                "image"=>"produit5",
                "prix"=>110,
                "promo"=> null,
                "stock"=>11,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Chaussures Nike",
                "categorie"=>"Chaussures",
                "couleur"=>"Orange",
                "image"=>"produit6",
                "prix"=>95,
                "promo"=> null,
                "stock"=>6,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Ballon Maroc",
                "categorie"=>"Ballons",
                "couleur"=>"Rouge",
                "image"=>"produit7",
                "prix"=>45,
                "promo"=> null,
                "stock"=>7,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Maillot Manchester",
                "categorie"=>"Maillots",
                "couleur"=>"Rouge",
                "image"=>"produit8",
                "prix"=>95,
                "promo"=> 20,
                "stock"=>5,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Maillot Chelsea",
                "categorie"=>"Maillots",
                "couleur"=>"Bleu",
                "image"=>"produit9",
                "prix"=>100,
                "promo"=> null,
                "stock"=>2,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Chaussures Nike",
                "categorie"=>"Chaussures",
                "couleur"=>"Noir",
                "image"=>"produit10",
                "prix"=>85,
                "promo"=> null,
                "stock"=>13,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Protèges Tibia",
                "categorie"=>"Accessoires",
                "couleur"=>"Noir",
                "image"=>"produit11",
                "prix"=>40,
                "promo"=> null,
                "stock"=>7,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Ballon UCL",
                "categorie"=>"Ballons",
                "couleur"=>"Blanc",
                "image"=>"produit12",
                "prix"=>60,
                "promo"=> 20,
                "stock"=>3,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Maillot Liverpool",
                "categorie"=>"Liverpool",
                "couleur"=>"Rouge",
                "image"=>"produit13",
                "prix"=>105,
                "promo"=> null,
                "stock"=>6,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Chaussures Nike",
                "categorie"=>"Chaussures",
                "couleur"=>"Jaune",
                "image"=>"produit14",
                "prix"=>118,
                "promo"=> null,
                "stock"=>4,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Brassard",
                "categorie"=>"Accessoires",
                "couleur"=>"Orange",
                "image"=>"produit15",
                "prix"=>70,
                "promo"=> null,
                "stock"=>7,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Chaussures Nike",
                "categorie"=>"Chaussures",
                "couleur"=>"Bleu",
                "image"=>"produit16",
                "prix"=>95,
                "promo"=> 20,
                "stock"=>10,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Ballon Liga",
                "categorie"=>"Ballons",
                "couleur"=>"Blanc",
                "image"=>"produit17",
                "prix"=>45,
                "promo"=> null,
                "stock"=>8,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Maillot Pays-Bas",
                "categorie"=>"Chaussures",
                "couleur"=>"Orange",
                "image"=>"produit18",
                "prix"=>80,
                "promo"=> null,
                "stock"=>4,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Protèges tibias",
                "categorie"=>"Accessoires",
                "couleur"=>"Noir",
                "image"=>"produit19",
                "prix"=>35,
                "promo"=> null,
                "stock"=>7,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Chaussures Adidas",
                "categorie"=>"Chaussures",
                "couleur"=>"Blanc",
                "image"=>"produit20",
                "prix"=>80,
                "promo"=> 20,
                "stock"=>15,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Chausssures Nike",
                "categorie"=>"Chaussures",
                "couleur"=>"Jaune",
                "image"=>"produit21",
                "prix"=>140,
                "promo"=> 20,
                "stock"=>1,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Maillot PSG",
                "categorie"=>"Maillots",
                "couleur"=>"Bleu",
                "image"=>"produit22",
                "prix"=>130,
                "promo"=> 20,
                "stock"=>3,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Chaussures Nike",
                "categorie"=>"Chaussures",
                "couleur"=>"Noir",
                "image"=>"produit23",
                "prix"=>100,
                "promo"=> null,
                "stock"=>6,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Ballon Real Madrid",
                "categorie"=>"Ballons",
                "couleur"=>"Bleu",
                "image"=>"produit24",
                "prix"=>80,
                "promo"=> 20,
                "stock"=>4,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
            [
                "nom"=>"Chaussures Adidas",
                "categorie"=>"Chaussures",
                "couleur"=>"Blanc",
                "image"=>"produit25",
                "prix"=>80,
                "promo"=> null,
                "stock"=>9,
                "description"=>"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam tempora perspiciatis nisi at ipsa aperiam officiis molestiae, unde culpa repudiandae.",
            ],
        ]);
    }
}
